# .github/workflows/main.yml
name: PackageRouteAI Test Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-report:
    runs-on: ubuntu-latest # Use a Linux environment for consistency

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Get your code from the repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # Or a newer version like '3.10', '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Pillow # Ensure Pillow is installed

      - name: Set up Java for Allure (required by Allure Command Line)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # A common OpenJDK distribution
          java-version: "17" # Java 17 is a good LTS version

      - name: Install Allure Command Line
        run: |
          npm install -g allure-commandline # Use npm to install Allure CLI

      - name: Create .env file for SUT URL
        run: |
          echo "PRIME_VISION_SUT_API_BASE_URL=http://localhost:5000" >> .env

      - name: Run Pytest tests and generate Allure results
        run: |
          pytest --alluredir=allure-results # Output raw results to 'allure-results' folder

      # --- REMOVE THE OLD "GENERATE ALLURE REPORT" STEP HERE ---
      # --- ADD THE NEW MANUAL GENERATION STEP BELOW ---

      - name: Generate Allure Report (Manual) # NEW STEP
        if: always() # Runs even if tests fail, so you always get a report
        run: |
          allure generate allure-results --clean -o allure-report
          # This command takes the raw 'allure-results' and creates the HTML report
          # in a new folder named 'allure-report'.
          # '--clean' ensures the output directory is clean before generation.

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report # <-- IMPORTANT: CHANGE THIS TO THE NEW OUTPUT FOLDER
          force_orphan: true
